server:
  port: 8083
spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://nebula:nebula@localhost:27017/nebula_notification?authSource=admin}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8180/realms/nebulaops/protocol/openid-connect/certs}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: notification-service
nebulaops:
  security:
    enabled: ${KEYCLOAK_AUTH_ENABLED:false}
