name: nebulaops-v22-5
services:
  release-orchestrator-service:
    environment:
      SPRING_PROFILES_ACTIVE: local
      NEBULAOPS_COMPONENT: release-orchestrator-service
      NEBULAOPS_VERSION: 22.5.0
  policy-governance-service:
    environment:
      SPRING_PROFILES_ACTIVE: local
      NEBULAOPS_COMPONENT: policy-governance-service
      NEBULAOPS_VERSION: 22.5.0
  audit-service:
    environment:
      SPRING_PROFILES_ACTIVE: local
      NEBULAOPS_COMPONENT: audit-service
      NEBULAOPS_VERSION: 22.5.0
  mfe-infra-hub:
    labels:
    - nebulaops.module=infra-hub
    - nebulaops.version=22.5.0
  mfe-release-center:
    labels:
    - nebulaops.module=release-center
    - nebulaops.version=22.5.0
  mfe-policy-center:
    labels:
    - nebulaops.module=policy-center
    - nebulaops.version=22.5.0
  mfe-notification-center:
    labels:
    - nebulaops.module=notification-center
    - nebulaops.version=22.5.0
