// NebulaOps v22.2 - This MFE has been migrated to Angular 18.
// The remoteEntry.js at runtime is generated by: npm run build
// The Angular build outputs to dist/ and nginx serves dist/browser/
// Custom element tag is registered in src/main.ts via @angular/elements.
//
// To develop locally:
//   cd frontend/remotes/cicd-gitops
//   npm install --legacy-peer-deps
//   npm start   (ng serve --port <port>)
//
// To build for production:
//   npm run build
//
// Docker:
//   docker build -t nebulaops-mfe-cicd-gitops:22.2 .
