apiVersion: v1
kind: Service
metadata:
  name: {{ include "springMvcAddon.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "springMvcAddon.labels" . | nindent 4 }}
spec:
  selector:
    app: spring-mvc-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
