apiVersion: v2
name: nebulaops
description: Helm chart for the NebulaOps Angular + Spring Boot + MongoDB + RabbitMQ + Redis platform
type: application
version: 23.2.0
appVersion: "23.2.0"
keywords:
  - spring-boot
  - angular
  - mongodb
  - rabbitmq
  - redis
  - grafana
  - operations
maintainers:
  - name: Peyman Eshghi Malayeri
