apiVersion: v2
name: nebulaops
description: Helm chart for the NebulaOps Angular + Spring Boot + MongoDB + RabbitMQ + Redis platform
type: application
version: 22.5.0
appVersion: "22.5.0"
keywords:
  - spring-boot
  - angular
  - mongodb
  - rabbitmq
  - redis
  - grafana
  - portfolio
maintainers:
  - name: Peyman Eshghi Malayeri
