apiVersion: v2
name: nebulaops
description: Helm chart for the NebulaOps Angular + Spring Boot + MongoDB + Kafka platform
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - spring-boot
  - angular
  - mongodb
  - kafka
  - grafana
  - portfolio
maintainers:
  - name: Peyman Eshghi Malayeri
