spring.application.name=APIForge
server.port=8080
server.servlet.context-path=/apiforge
server.forward-headers-strategy=framework
spring.jackson.serialization.indent-output=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
