{ { - if .Values.kafka.enabled } }
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebulaops-kafka
  namespace: { { .Values.global.namespace } }
spec:
  replicas: 1
  selector:
    matchLabels: { app: nebulaops-kafka }
  template:
    metadata:
      labels: { app: nebulaops-kafka }
    spec:
      containers:
        - name: kafka
          image: { { .Values.kafka.image } }
          ports:
            - containerPort: { { .Values.kafka.port } }
          env:
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "1@127.0.0.1:9093"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://nebulaops-kafka:9092"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: nebulaops-kafka
  namespace: { { .Values.global.namespace } }
spec:
  selector: { app: nebulaops-kafka }
  ports:
    - port: { { .Values.kafka.port } }
      targetPort: { { .Values.kafka.port } }
  { { - end } }
