{ { - if .Values.redis.enabled } }
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebulaops-redis
  namespace: { { .Values.global.namespace } }
spec:
  replicas: 1
  selector: { matchLabels: { app: nebulaops-redis } }
  template:
    metadata: { labels: { app: nebulaops-redis } }
    spec:
      containers:
        - name: redis
          image: { { .Values.redis.image } }
          ports: [ { containerPort: { { .Values.redis.port } } } ]
---
apiVersion: v1
kind: Service
metadata:
  name: nebulaops-redis
  namespace: { { .Values.global.namespace } }
spec:
  selector: { app: nebulaops-redis }
  ports: [ { port: { { .Values.redis.port } }, targetPort: { { .Values.redis.port } } } ]
  { { - end } }
---
  { { - if .Values.rabbitmq.enabled } }
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebulaops-rabbitmq
  namespace: { { .Values.global.namespace } }
spec:
  replicas: 1
  selector: { matchLabels: { app: nebulaops-rabbitmq } }
  template:
    metadata: { labels: { app: nebulaops-rabbitmq } }
    spec:
      containers:
        - name: rabbitmq
          image: { { .Values.rabbitmq.image } }
          ports:
            - { containerPort: { { .Values.rabbitmq.port } } }
            - { containerPort: { { .Values.rabbitmq.managementPort } } }
          env:
            - { name: RABBITMQ_DEFAULT_USER, value: { { .Values.rabbitmq.username | quote } } }
            - { name: RABBITMQ_DEFAULT_PASS, value: { { .Values.rabbitmq.password | quote } } }
---
apiVersion: v1
kind: Service
metadata:
  name: nebulaops-rabbitmq
  namespace: { { .Values.global.namespace } }
spec:
  selector: { app: nebulaops-rabbitmq }
  ports:
    - { name: amqp, port: { { .Values.rabbitmq.port } }, targetPort: { { .Values.rabbitmq.port } } }
    - { name: management, port: { { .Values.rabbitmq.managementPort } }, targetPort: { { .Values.rabbitmq.managementPort } } }
  { { - end } }
