apiVersion: v1
kind: Secret
metadata:
  name: nebulaops-secrets
  namespace: { { .Values.global.namespace } }
type: Opaque
stringData:
  MONGO_USERNAME: { { .Values.mongodb.username | quote } }
  MONGO_PASSWORD: { { .Values.mongodb.password | quote } }
  GRAFANA_ADMIN_USER: { { .Values.observability.grafana.adminUser | quote } }
  GRAFANA_ADMIN_PASSWORD: { { .Values.observability.grafana.adminPassword | quote } }
