apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nebulaops
  namespace: argocd
spec:
  description: NebulaOps GitOps project
  sourceRepos:
    - '*'
  destinations:
    - namespace: nebulaops
      server: https://kubernetes.default.svc
    - namespace: nebulaops-dev
      server: https://kubernetes.default.svc
    - namespace: nebulaops-staging
      server: https://kubernetes.default.svc
    - namespace: nebulaops-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: cicd-sync
      description: Allows GitLab CI to sync NebulaOps applications
      policies:
        - p, proj:nebulaops:cicd-sync, applications, sync, nebulaops/*, allow
        - p, proj:nebulaops:cicd-sync, applications, get, nebulaops/*, allow
