server:
  port: 8084
spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://nebula:nebula@localhost:27017/nebula_file?authSource=admin}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  metrics:
    tags:
      application: file-service
