#!/usr/bin/env bash
# NebulaOps v24.1 frontend image builder.
# Requires dist folders generated by ./scripts/wsl/build-frontend-local.sh
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

services=(
  frontend
  mfe-platform-catalog
  mfe-incident-command-center
  mfe-runtime-readiness
  mfe-docker-storage-cleanup
  mfe-environment-configuration
  mfe-dependency-impact
  mfe-test-quality-dashboard
  mfe-docker-desktop
  mfe-openlens-kubernetes
  mfe-task-management
  mfe-observability
  mfe-cicd-gitops
  mfe-terraform-studio
  mfe-devsecops
  mfe-ai-ops
  mfe-finops-cost
  mfe-infra-hub
  mfe-release-center
  mfe-policy-center
  mfe-notification-center
  mfe-identity-admin
  mfe-progressive-delivery
)

check_dist() {
  local svc="$1"
  local path
  if [ "$svc" = "frontend" ]; then
    path="frontend/dist/nebulaops/browser/index.html"
  else
    local remote="${svc#mfe-}"
    path="frontend/remotes/${remote}/dist/browser/index.html"
  fi

  if [ ! -f "$path" ]; then
    echo "[ERROR] Missing dist for ${svc}: $path"
    echo "Run first: ./scripts/wsl/build-frontend-local.sh"
    exit 1
  fi
}

for svc in "${services[@]}"; do
  check_dist "$svc"
done

echo "[NebulaOps] Building frontend runtime images from prebuilt dist"
for svc in "${services[@]}"; do
  echo
  echo "==> docker compose build ${svc}"
  docker compose build --progress=plain "$svc"
done

echo
echo "[NebulaOps] Frontend runtime images completed."
