#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TOOLS_DIR="$ROOT_DIR/.runtime-tools"
mkdir -p "$TOOLS_DIR"

copy_tool() {
  local name="$1"
  local required="${2:-optional}"
  local src=""
  if command -v "$name" >/dev/null 2>&1; then
    src="$(command -v "$name")"
    cp -L "$src" "$TOOLS_DIR/$name"
    chmod 0755 "$TOOLS_DIR/$name"
    echo "OK mounted runtime tool: $name -> $TOOLS_DIR/$name"
  else
    rm -f "$TOOLS_DIR/$name"
    if [[ "$required" == "required" ]]; then
      echo "WARN required runtime tool missing on host: $name" >&2
    else
      echo "INFO optional runtime tool missing on host: $name" >&2
    fi
  fi
}

copy_tool docker required
copy_tool kubectl required
copy_tool helm optional
copy_tool trivy optional
copy_tool terraform optional
copy_tool argocd optional

cat > "$TOOLS_DIR/README.md" <<'INFO'
This directory is generated by scripts/wsl/prepare-runtime-tools.sh.
It contains host CLI binaries copied into a bind-mounted folder for backend containers.
Backends do not return fake data; if a required tool is missing, endpoints return live:false with toolStatus.
INFO

echo "Runtime tools prepared in: $TOOLS_DIR"
