apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-mvc-service
  namespace: nebulaops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: spring-mvc.nebulaops.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-mvc-service
                port:
                  number: 8099
