apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-mvc-service
  namespace: nebulaops
  labels:
    app: spring-mvc-service
    app.kubernetes.io/name: spring-mvc-service
    app.kubernetes.io/part-of: nebulaops
    app.kubernetes.io/version: "23.4.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-mvc-service
  template:
    metadata:
      labels:
        app: spring-mvc-service
        app.kubernetes.io/name: spring-mvc-service
        app.kubernetes.io/part-of: nebulaops
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8099"
    spec:
      containers:
        - name: spring-mvc-service
          image: nebulaops-v23-4-spring-mvc-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8099
          env:
            - name: SERVER_PORT
              value: "8099"
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: APP_DISPLAY_NAME
              value: NebulaOps Spring MVC Service
            - name: APP_ENVIRONMENT
              value: kubernetes
            - name: NEBULAOPS_GATEWAY_URL
              value: http://gateway-service:8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 45
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 5
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: spring-mvc-service
  namespace: nebulaops
  labels:
    app: spring-mvc-service
    app.kubernetes.io/name: spring-mvc-service
    app.kubernetes.io/part-of: nebulaops
spec:
  selector:
    app: spring-mvc-service
  ports:
    - name: http
      port: 8099
      targetPort: http
