server:
  port: 8087
spring:
  application:
    name: pipeline-engine-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:8180/realms/nebulaops/protocol/openid-connect/certs}
jwt:
  secret: ${JWT_SECRET:nebulaops-v22-4-dev-secret-key-min-32-chars!!}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: pipeline-engine-service
nebulaops:
  security:
    enabled: ${KEYCLOAK_AUTH_ENABLED:false}
