import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  standalone: true,
  template: '<div class="live-only-source">NebulaOps live endpoint remote. Runtime bundle is generated by build-remote-entry.cjs and reads only /api/** endpoints.</div>',
  styles: ['.live-only-source{padding:24px;color:#eaf4ff;background:#050816;font-family:Inter,system-ui,sans-serif}']
})
export class AppComponent {}
