apiVersion: v1
kind: ConfigMap
metadata:
  name: nebulaops-config
  namespace: nebulaops
data:
  RABBITMQ_HOST: rabbitmq
  AUTH_SERVICE_URL: http://auth-service:8081
  TASK_SERVICE_URL: http://task-service:8082
  FILE_SERVICE_URL: http://file-service:8084
