apiVersion: v1
kind: Secret
metadata:
  name: nebulaops-secrets
  namespace: nebulaops
type: Opaque
stringData:
  DB_USER: nebula
  DB_PASSWORD: replace-me
  JWT_SECRET: replace-with-strong-32-byte-secret
